import type { Product } from '@/lib/types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (slug: string) => {
  const image = PlaceHolderImages.find(p => p.id === slug);
  return image ? image.imageUrl : 'https://picsum.photos/seed/placeholder/600/400';
}

const getImageHint = (slug: string) => {
    const image = PlaceHolderImages.find(p => p.id === slug);
    return image ? image.imageHint : 'singing bowl';
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Zen Harmony Bowl',
    slug: 'zen-harmony-bowl',
    description: 'A beautifully crafted 7-inch bowl made from a seven-metal alloy, perfect for deep meditation and achieving a state of tranquility. Its long-lasting resonance helps in focusing the mind.',
    price: 99.99,
    imageUrl: getImage('zen-harmony-bowl'),
    imageHint: getImageHint('zen-harmony-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '2',
    name: 'Resonance Master Bowl',
    slug: 'resonance-master-bowl',
    description: 'A large 12-inch bowl with powerful, deep sound projection. Ideal for sound healing practitioners and group sessions. Its profound vibrations can be felt throughout the body.',
    price: 249.99,
    imageUrl: getImage('resonance-master-bowl'),
    imageHint: getImageHint('resonance-master-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '3',
    name: 'Serenity Now Bowl',
    slug: 'serenity-now-bowl',
    description: 'Compact and easy to transport, this 4-inch bowl brings instant calm wherever you go. Perfect for office stress relief or as a travel companion for mindfulness on the move.',
    price: 59.99,
    imageUrl: getImage('serenity-now-bowl'),
    imageHint: getImageHint('serenity-now-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '4',
    name: 'Tibetan Thunder Bowl',
    slug: 'tibetan-thunder-bowl',
    description: 'A traditional hand-hammered Tibetan bowl, 9 inches in diameter. It produces a deep, resonant hum with complex overtones, grounding you in the present moment.',
    price: 179.99,
    imageUrl: getImage('tibetan-thunder-bowl'),
    imageHint: getImageHint('tibetan-thunder-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '5',
    name: 'Crystal Chakra Bowl',
    slug: 'crystal-chakra-bowl',
    description: 'A stunning 8-inch frosted quartz crystal bowl tuned to the frequency of the heart chakra (F note). Its pure, high-frequency tone is ideal for chakra alignment and energy work.',
    price: 199.99,
    imageUrl: getImage('crystal-chakra-bowl'),
    imageHint: getImageHint('crystal-chakra-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '6',
    name: 'Himalayan Heart Bowl',
    slug: 'himalayan-heart-bowl',
    description: 'Hand-hammered by artisans in the Himalayan foothills, this 6-inch bowl has a uniquely warm and inviting tone. It is perfect for loving-kindness meditation and cultivating compassion.',
    price: 129.99,
    imageUrl: getImage('himalayan-heart-bowl'),
    imageHint: getImageHint('himalayan-heart-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '7',
    name: 'Moonlight Meditation Bowl',
    slug: 'moonlight-meditation-bowl',
    description: 'A silvery 10-inch bowl with ethereal tones that evoke the tranquility of moonlit nights. Perfect for evening meditation practices and lucid dreaming preparation.',
    price: 159.99,
    imageUrl: getImage('moonlight-meditation-bowl'),
    imageHint: getImageHint('moonlight-meditation-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '8',
    name: 'Solar Plexus Resonator',
    slug: 'solar-plexus-resonator',
    description: 'Tuned to E note (solar plexus chakra), this 7-inch golden-hued bowl empowers personal will and confidence. Its bright, energizing tone helps overcome self-doubt.',
    price: 139.99,
    imageUrl: getImage('solar-plexus-resonator'),
    imageHint: getImageHint('solar-plexus-resonator'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '9',
    name: 'Ancient Wisdom Bowl',
    slug: 'ancient-wisdom-bowl',
    description: 'A rare antique-style 11-inch bowl crafted using centuries-old techniques. Its complex harmonic overtones create a meditative soundscape that deepens spiritual practice.',
    price: 299.99,
    imageUrl: getImage('ancient-wisdom-bowl'),
    imageHint: getImageHint('ancient-wisdom-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '10',
    name: 'Pocket Peace Bowl',
    slug: 'pocket-peace-bowl',
    description: 'An ultra-portable 3-inch mini bowl that fits in your pocket or purse. Despite its small size, it produces a surprisingly clear and calming tone for on-the-go mindfulness.',
    price: 39.99,
    imageUrl: getImage('pocket-peace-bowl'),
    imageHint: getImageHint('pocket-peace-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '11',
    name: 'Crown Chakra Crystal Bowl',
    slug: 'crown-chakra-crystal-bowl',
    description: 'A pristine 9-inch clear quartz crystal bowl tuned to B note (crown chakra). Its celestial tones facilitate spiritual connection and higher consciousness expansion.',
    price: 279.99,
    imageUrl: getImage('crown-chakra-crystal-bowl'),
    imageHint: getImageHint('crown-chakra-crystal-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '12',
    name: 'Throat Chakra Soother',
    slug: 'throat-chakra-soother',
    description: 'Tuned to G note (throat chakra), this 6-inch blue-tinted bowl helps unlock authentic self-expression and clear communication. Ideal for speakers, singers, and truth-seekers.',
    price: 119.99,
    imageUrl: getImage('throat-chakra-soother'),
    imageHint: getImageHint('throat-chakra-soother'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '13',
    name: 'Forest Whisper Bowl',
    slug: 'forest-whisper-bowl',
    description: 'A handcrafted 8-inch bowl with earthy green patina. Its gentle, rustling tones evoke the serenity of ancient forests, perfect for nature-connected meditation.',
    price: 149.99,
    imageUrl: getImage('forest-whisper-bowl'),
    imageHint: getImageHint('forest-whisper-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '14',
    name: 'Root Chakra Grounding Bowl',
    slug: 'root-chakra-grounding-bowl',
    description: 'A deep-toned 10-inch bowl tuned to C note (root chakra). Its powerful bass resonance provides a sense of safety, stability, and connection to the earth.',
    price: 189.99,
    imageUrl: getImage('root-chakra-grounding-bowl'),
    imageHint: getImageHint('root-chakra-grounding-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '15',
    name: 'Third Eye Awakener',
    slug: 'third-eye-awakener',
    description: 'An indigo-hued 7-inch bowl tuned to A note (third eye chakra). Enhances intuition, inner wisdom, and clarity of vision during meditation and introspection.',
    price: 169.99,
    imageUrl: getImage('third-eye-awakener'),
    imageHint: getImageHint('third-eye-awakener'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '16',
    name: 'Beginner\'s Bliss Bowl',
    slug: 'beginners-bliss-bowl',
    description: 'A user-friendly 5-inch bowl perfect for those new to sound healing. Easy to play with a balanced tone, it includes a cushion and wooden striker.',
    price: 79.99,
    imageUrl: getImage('beginners-bliss-bowl'),
    imageHint: getImageHint('beginners-bliss-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '17',
    name: 'Ocean Wave Crystal Bowl',
    slug: 'ocean-wave-crystal-bowl',
    description: 'A stunning 11-inch aqua-colored crystal bowl with fluid, wave-like tones. Its soothing sounds mimic ocean rhythms, excellent for deep relaxation and stress relief.',
    price: 319.99,
    imageUrl: getImage('ocean-wave-crystal-bowl'),
    imageHint: getImageHint('ocean-wave-crystal-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '18',
    name: 'Sacral Chakra Flow Bowl',
    slug: 'sacral-chakra-flow-bowl',
    description: 'Tuned to D note (sacral chakra), this warm orange-toned 6-inch bowl awakens creativity, passion, and emotional flow. Great for artists and those seeking inspiration.',
    price: 109.99,
    imageUrl: getImage('sacral-chakra-flow-bowl'),
    imageHint: getImageHint('sacral-chakra-flow-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '19',
    name: 'Master Healer\'s Bowl Set',
    slug: 'master-healers-bowl-set',
    description: 'A professional set of seven bowls, each tuned to a different chakra frequency. Complete with carrying case, mallets, and cushions for comprehensive sound therapy.',
    price: 899.99,
    imageUrl: getImage('master-healers-bowl-set'),
    imageHint: getImageHint('master-healers-bowl-set'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
  {
    id: '20',
    name: 'Sunrise Awakening Bowl',
    slug: 'sunrise-awakening-bowl',
    description: 'A luminous 8-inch bowl with golden sunrise hues. Its uplifting, energizing tones are perfect for morning meditation and setting positive intentions for the day.',
    price: 154.99,
    imageUrl: getImage('sunrise-awakening-bowl'),
    imageHint: getImageHint('sunrise-awakening-bowl'),
    audioUrl: 'https://r2.fivemanage.com/s1eqtVnkFslLnri1MNmBV/singingbowl_sound1.mp3',
  },
];
